#!/bin/bash

# YOLOv8 MLOps Bootstrap Script
# Creates the Terraform state backend infrastructure

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo "=========================================="
echo "YOLOv8 MLOps - Bootstrap State Backend"
echo "=========================================="

# Check prerequisites
check_prerequisites() {
    echo -e "\n${YELLOW}Checking prerequisites...${NC}"

    if ! command -v aws &> /dev/null; then
        echo -e "${RED}✗ AWS CLI not found${NC}"
        exit 1
    fi
    echo -e "${GREEN}✓ AWS CLI installed${NC}"

    if ! command -v terraform &> /dev/null; then
        echo -e "${RED}✗ Terraform not found${NC}"
        exit 1
    fi
    echo -e "${GREEN}✓ Terraform installed${NC}"

    # Check AWS credentials
    if ! aws sts get-caller-identity &> /dev/null; then
        echo -e "${RED}✗ AWS credentials not configured${NC}"
        exit 1
    fi
    echo -e "${GREEN}✓ AWS credentials configured${NC}"
}

# Get AWS account info
get_aws_info() {
    AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
    AWS_USER=$(aws sts get-caller-identity --query Arn --output text)

    echo -e "\n${BLUE}AWS Account Information:${NC}"
    echo "  Account ID: $AWS_ACCOUNT_ID"
    echo "  User/Role: $AWS_USER"
}

# Get user inputs
get_inputs() {
    echo -e "\n${YELLOW}Bootstrap Configuration${NC}"
    echo "Please provide the following information:"
    echo ""

    # Project name
    read -p "Project name [yolov8-mlops]: " PROJECT_NAME
    PROJECT_NAME=${PROJECT_NAME:-yolov8-mlops}

    # AWS region
    read -p "AWS region [us-east-1]: " AWS_REGION
    AWS_REGION=${AWS_REGION:-us-east-1}

    # Generate a unique bucket name
    RANDOM_SUFFIX=$(openssl rand -hex 4)
    DEFAULT_BUCKET="${PROJECT_NAME}-tf-state-${RANDOM_SUFFIX}"

    read -p "S3 bucket name [$DEFAULT_BUCKET]: " STATE_BUCKET
    STATE_BUCKET=${STATE_BUCKET:-$DEFAULT_BUCKET}

    # DynamoDB table name
    DEFAULT_TABLE="${PROJECT_NAME}-tf-lock"
    read -p "DynamoDB table name [$DEFAULT_TABLE]: " DYNAMODB_TABLE
    DYNAMODB_TABLE=${DYNAMODB_TABLE:-$DEFAULT_TABLE}

    echo -e "\n${GREEN}Configuration Summary:${NC}"
    echo "  Project Name: $PROJECT_NAME"
    echo "  AWS Region: $AWS_REGION"
    echo "  S3 Bucket: $STATE_BUCKET"
    echo "  DynamoDB Table: $DYNAMODB_TABLE"
    echo ""
}

# Create terraform.tfvars
create_tfvars() {
    echo -e "\n${YELLOW}Creating terraform.tfvars...${NC}"

    cat > infra/bootstrap/terraform.tfvars <<EOF
# Auto-generated by bootstrap.sh
aws_region          = "$AWS_REGION"
project_name        = "$PROJECT_NAME"
state_bucket_name   = "$STATE_BUCKET"
dynamodb_table_name = "$DYNAMODB_TABLE"

enable_point_in_time_recovery = true
state_retention_days          = 90
EOF

    echo -e "${GREEN}✓ terraform.tfvars created${NC}"
}

# Deploy bootstrap infrastructure
deploy_bootstrap() {
    echo -e "\n${YELLOW}Deploying bootstrap infrastructure...${NC}"
    echo "This will create:"
    echo "  - S3 bucket for Terraform state"
    echo "  - S3 bucket for access logs"
    echo "  - DynamoDB table for state locking"
    echo "  - IAM policy for state access"
    echo ""

    read -p "Continue with deployment? (yes/no): " CONFIRM
    if [ "$CONFIRM" != "yes" ]; then
        echo "Aborted."
        exit 0
    fi

    cd infra/bootstrap

    # Initialize Terraform
    echo -e "\n${YELLOW}Initializing Terraform...${NC}"
    terraform init

    # Plan
    echo -e "\n${YELLOW}Planning infrastructure...${NC}"
    terraform plan -out=bootstrap.tfplan

    # Apply
    echo -e "\n${YELLOW}Applying infrastructure...${NC}"
    terraform apply bootstrap.tfplan

    echo -e "\n${GREEN}✓ Bootstrap infrastructure deployed!${NC}"

    cd ../..
}

# Display next steps
show_next_steps() {
    echo -e "\n${GREEN}=========================================="
    echo "Bootstrap Complete!"
    echo "==========================================${NC}"

    # Get outputs
    cd infra/bootstrap
    BUCKET=$(terraform output -raw state_bucket_name)
    TABLE=$(terraform output -raw dynamodb_table_name)

    echo -e "\n${BLUE}State Backend Configuration:${NC}"
    echo "  S3 Bucket: $BUCKET"
    echo "  DynamoDB Table: $TABLE"

    echo -e "\n${YELLOW}Next Steps:${NC}"
    echo ""
    echo "1. Update infra/provider.tf with the backend configuration:"
    echo "   ${GREEN}terraform output -raw backend_config_hcl${NC}"
    echo ""
    echo "2. Initialize the main infrastructure:"
    echo "   ${GREEN}cd infra && terraform init${NC}"
    echo ""
    echo "3. Deploy the main infrastructure:"
    echo "   ${GREEN}terraform plan${NC}"
    echo "   ${GREEN}terraform apply${NC}"
    echo ""
    echo -e "${BLUE}Backend configuration for infra/provider.tf:${NC}"
    terraform output -raw backend_config_hcl

    cd ../..
}

# Main execution
main() {
    check_prerequisites
    get_aws_info
    get_inputs
    create_tfvars
    deploy_bootstrap
    show_next_steps
}

main
